name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      ANDROID_API: 21 
      ABIS: "arm64-v8a armeabi-v7a"

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake libtool pkg-config python3 curl unzip git

      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: 'r25c'

      - name: Export NDK path
        run: |
          echo "ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV
          echo "NDK=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV
          echo "PATH=${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH" >> $GITHUB_ENV

      - name: Run dependency build + ndk-build
        run: |
          chmod +x ./build_all_android.sh
          ./build_all_android.sh

      - name: chmod +x gradlew
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set variables
        run: |
          echo "version=v$(grep versionName app/build.gradle | awk -F\" '{print $2}')" >> $GITHUB_ENV
          echo "commit=$(echo ${{ github.sha }} | cut -c-7)" >> $GITHUB_ENV
          echo "repo=$(echo ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/})" >> $GITHUB_ENV
          echo "timestamp=$(TZ='Asia/Tokyo' date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
          echo "name=${repo}-${version}-${commit}-${timestamp}" >> $GITHUB_ENV

      - name: Show set variables
        run: |
          echo -e "version=${{ env.version }}"
          echo -e "commit=${{ env.commit }}"
          echo -e "repo=${{ env.repo }}"
          echo -e "timestamp=${{ env.timestamp }}"
          echo -e "name=${{ env.name }}"

      - name: Build APK
        run: |
          ./gradlew --no-daemon --stacktrace --warning-mode=all assembleRelease
          mv -vf app/build/outputs/apk/release/app-release.apk "${{ env.name }}.apk"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.name }}"
          path: "${{ env.name }}.apk"
